# SITE CONFIGURATION
title: MediWise # your site title
author: MediWise, LLC # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mediwise.us/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: MediWise, LLC
  #COMMENTING OUT FOR NOW
  #links:
   # - https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    #- https://www.linkedin.com/in/BenBalter
  

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Medical Translation', link: '/translation'}
    - {name: 'Regulatory Strategy', link: '/strategy'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Medical Technical Writing, Regulatory Affairs Strategy Consulting, Medical Translation

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: webforms@mediwise.us # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
